name: test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'resources.md'  
      - 'docs/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: build tools
      run: | 
        cd tools && for i in ./*.go; do go build "$i"; done && cd ..
    - name: Test
      run: tools/build
      env:
        VERBOSE: 1
        TESTING: 1
